# Generated by Django 3.0.5 on 2021-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkinson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=200)),
                ('stepsNum', models.IntegerField()),
            ],
        ),
    ]
