# Generated by Django 2.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkinson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login',models.CharField(max_length=70, blank=False, default='')),
                 ('password', models.CharField(max_length=200,blank=False, default='')),
                ('stepsNum' , models.IntegerField()),
            ],
        ),
    ]